name: rossmann_store_sales
channels:
  - conda-forge
dependencies:
  - python=3.6
  - click
  - sphinx
  - coverage
  - flake8
  - pandas=0.22.0
  - numpy=1.14.2
  - matplotlib=2.2.0
  - seaborn==0.8.1
  - engarde
  - fbprophet
  - pip:
    - -e .
